logging:
    level:
        root: INFO

server:
    port: 6657
    #    ssl:
    #        enabled: false
    #        key-store-type: PKCS12
    #        key-password: jTwcbCw7
    #        key-alias: tomcat
    #        key-store: api.eyeque.vip.pfx
    servlet:
        encoding:
            force: true
            enabled: true
            charset: utf-8
    context-path: /


spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
    security:
        ignored=/**:
management:
    endpoints:
        enabled-by-default: false

security:
    ignored=/**: